[package]
name = "chapeau"
version = "0.1.0"
edition = "2021"
description = "Fedora-native system state and relationship manager"
license = "MIT"
authors = ["Soulaymane01"]
repository = "https://github.com/Soulaymane01/chapeau"
homepage = "https://github.com/Soulaymane01/chapeau"
readme = "README.md"
keywords = ["fedora", "dnf", "systemd", "flatpak", "system"]
categories = ["command-line-utilities", "system"]
exclude = ["gui", "branding", "packaging", ".github"]

[workspace]
members = ["gui"]
default-members = ["."]
resolver = "2"

[dependencies]
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.32", features = ["bundled"] }
petgraph = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
anyhow = "1"
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
zbus = "5"
zbus_systemd = { version = "0.26100.0", features = ["systemd1"] }
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
tempfile = "3"
